### ISSUE TITLE
Improvements for Alpha Version 2

### ISSUE THREAD

**Issue by medallyon** [MichalisAntonas/Nightmare#2]
- [x] Implement Unity Analytics
  - https://analytics.cloud.unity3d.com/reporting/837f4102-a290-4076-9594-3ee62f7c17dd/
- [x] Standardise triggers and zombies to make proper use of prefabs
  - Create one prefab with a script that accepts target actors instead of having prefabs for each scenario, like how the jumpscare-triggers are set up right now
- [x] Based on feedback, the player doesn't lose health? Check this.
- [x] Ammo doesn't reset when finishing and restarting the game
- [x] There is no Death Soundbyte for Zombies
- [x] Gun Muzzle Flash
- [x] Better / more intense shooting soundbyte
- [ ] Zombie/Gunshot reactions (either animation or blood effect)

**Comment by MichalisAntonas** [comment]
- [x] Reduce ammo amount

- [x] Add an outline on collectables or a name above them 

- [x] Change gun collision so it doesn't phase through the walls 

- [x] Needs to be scarier, perhaps adding a jump scare would help.
